title: Xianghui Li's Homepage
page-top-title: Xianghui Li
top-section-bg-text: Integrated Circuit Design and Integrated System
home-subtitle: Xianghui Li&ensp;|&ensp;李相辉
copyright-text: '&copy; Xianghui Li 2025-2030. All Rights Reserved.'
