title: Xianghui Li's Homepage
page-top-title: Xianghui Li
top-section-bg-text: Integrated Circuit Design and Integrated System
home-subtitle: Xianghui Li&ensp;|&ensp;李相辉
copyright-text: '<p>&copy; 2025 Xianghui Li. All original content on this site is my own.</p> <p>The theme is created by Sen Li, and is licensed under the MIT License.</p>'
